Tokens poc
zeppelinlabs/util-components pull request #21
Opened 2022-12-16 01:14 UTC by ovveeerrrr

Aun falta el manejo de las tipografias con los tokens

2022-12-20 14:16 UTC, ovveeerrrr commented on scripts/GenerateTheme.ts
> +import { ObjectTyped } from "../src/util/ObjectTyped"
Done

2022-12-20 14:17 UTC, ovveeerrrr commented on scripts/GenerateTheme.ts
> +    generateTSFileExportConst("DefaultThemeTokens",
Done

2022-12-20 14:35 UTC, Persitz commented on scripts/generateDesignTokens/fontTokensHelper.ts
> +						return vWeight.value.fontFamily
habria que chequear el type que sea lo que queremos

2022-12-20 14:35 UTC, Persitz commented on scripts/generateDesignTokens/fontTokensHelper.ts
> +						return vWeight.value.fontFamily
podemos usar el FigmaTokenType

2022-12-20 14:36 UTC, Persitz requested changes
deje unas sugerencias menores, el resto ya esta pronto

2022-12-20 21:52 UTC, ovveeerrrr commented on scripts/generateDesignTokens/fontTokensHelper.ts
> +						return vWeight.value.fontFamily
Done

2022-12-22 19:18 UTC, Persitz commented on scripts/generateDesignTokens/fontTokensHelper.ts
> +						return vWeight.value.fontFamily
decia usar uno que ya habiamos hecho con los colores

2022-12-22 19:44 UTC, ovveeerrrr commented on scripts/generateDesignTokens/fontTokensHelper.ts
> +						return vWeight.value.fontFamily
Done, lo agregue en un archivo aparte para usarlo en ambas funciones

2022-12-22 20:05 UTC, Persitz approved these changes

2022-12-22 20:08 UTC, merged