Task/checkbox sync token
zeppelinlabs/util-components pull request #25
Opened 2023-01-02 18:34 UTC by sebastian-zeppelinlabs

2023-01-02 23:14 UTC, ovveeerrrr requested changes

2023-01-02 23:14 UTC, ovveeerrrr commented on src/components/Form/Checkbox/CheckboxStyles.ts
>  const Input = styled.input.attrs({ type: "checkbox", }) <Props>`
este: input.attrs({ type: "checkbox", }) para que se usa?

2023-01-02 23:14 UTC, ovveeerrrr commented on src/components/Form/Checkbox/CheckboxStyles.ts
> +        box-shadow: 0 0 0 ${UiTokens.borderWidth.size3} ${thp.primary.level200._};
el token borderWitdh es para el tamaño del border. en este caso como es el focus usemos el numero "4px"

2023-01-02 23:14 UTC, ovveeerrrr commented on src/components/Form/Checkbox/CheckboxStyles.ts
> +        border: none;
No lo cambiaria a border none. en un listado con varios inputs es probable que al hacer chec / uncheck los elementos en pantalla salten. deja el border con el mismo width y le pasas el mismo color de fondo asi queda igual

2023-01-02 23:14 UTC, ovveeerrrr commented on src/components/Form/Checkbox/CheckboxStyles.ts
> +    width: 70%;
Que hace este 70%?

2023-01-03 13:37 UTC, sebastian-zeppelinlabs commented on src/components/Form/Checkbox/CheckboxStyles.ts
>  const Input = styled.input.attrs({ type: "checkbox", }) <Props>`
Se utiliza para indicarle a styled-components que el elemento es un input de tipo checkbox. Se puede quitar ya que del lado de la lógica se está indicando ya que es un input de tipo checkbox, ya que se supone que indicarlo desde styled-components evita hacerlo desde react.

2023-01-03 13:43 UTC, sebastian-zeppelinlabs commented on src/components/Form/Checkbox/CheckboxStyles.ts
> +    width: 70%;
Es el tamaño del check o ícono interno al box. En 70% se encuentra con un aspecto muy semejante al del diseño, y además al ser una medida porcentual, esta escala con los distintos tamaños del box.

2023-01-03 13:47 UTC, sebastian-zeppelinlabs commented on src/components/Form/Checkbox/CheckboxStyles.ts
> +        border: none;
Done.

2023-01-03 13:47 UTC, sebastian-zeppelinlabs commented on src/components/Form/Checkbox/CheckboxStyles.ts
> +        box-shadow: 0 0 0 ${UiTokens.borderWidth.size3} ${thp.primary.level200._};
Done.

2023-01-03 18:28 UTC, ovveeerrrr commented on src/components/Form/Checkbox/CheckboxStyles.ts
>  const Input = styled.input.attrs({ type: "checkbox", }) <Props>`
Entiendo, sin embargo creo que deberiamos mantener una misma convencion. hacerlo aqui y en todos los estilos que retornen un input. Vi los inputs y todos se definen por el lado de la logica. Para no cambiarlos todos y afectar futuras logicas creo mejor mantener la previa convencion

2023-01-03 18:59 UTC, mateoZeppelin approved these changes

2023-01-04 16:11 UTC, sebastian-zeppelinlabs commented on src/components/Form/Checkbox/CheckboxStyles.ts
>  const Input = styled.input.attrs({ type: "checkbox", }) <Props>`
Done.

2023-01-04 20:25 UTC, ovveeerrrr approved these changes

2023-01-05 13:22 UTC, merged