Task/radio sync token
zeppelinlabs/util-components pull request #26
Opened 2023-01-02 19:00 UTC by sebastian-zeppelinlabs

2023-01-02 23:24 UTC, ovveeerrrr requested changes

2023-01-02 23:24 UTC, ovveeerrrr commented on src/components/Form/Checkbox/CheckboxStyles.ts
> +        box-shadow: 0 0 0 ${UiTokens.borderWidth.size3} ${thp.primary.level200._};
IDEM el token border width no se usa con las sombras

2023-01-02 23:24 UTC, ovveeerrrr commented on src/components/Form/Checkbox/CheckboxStyles.ts
> -        border: 1px solid ${thp.base.level1000._};
Idem no elimine el borde, cambie el color de borde con el mismo del fondo

2023-01-02 23:24 UTC, ovveeerrrr commented on src/components/Form/Checkbox/CheckboxStyles.ts
> +    width: 70%;
quizas width 100% y con el padding del padre se ajusta el elemento?

2023-01-02 23:24 UTC, ovveeerrrr commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> +        [RadioButtonSize.Small]: 16,
devuelva en un objeto en tamaño del circulo externo y aparte otra entrada con la separación que hay entre el circulo externo y el interno para darles mas opciones a los devs

2023-01-02 23:24 UTC, ovveeerrrr commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> +        width: 50%;
un width de 100% mas en el padre un padding con la nueva entrada del getRadio size ayuda a que el tamaño del circulo interno no quede tan magico

2023-01-02 23:24 UTC, ovveeerrrr commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> +       box-shadow: 0 0 0 ${UiTokens.borderWidth.size3} ${thp.primary.level200._};
IDEM con las demas sombras

2023-01-02 23:24 UTC, ovveeerrrr commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> -    ErrorMessageContainer,
Ya no se esta poniendo mensajes de error? ahora como se maneja?

2023-01-02 23:42 UTC, ovveeerrrr requested changes

2023-01-02 23:42 UTC, ovveeerrrr commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> -    max-width: 12px;
Porque se estan eliminado? veo que solo retorna el width

2023-01-03 13:48 UTC, sebastian-zeppelinlabs commented on src/components/Form/Checkbox/CheckboxStyles.ts
> +        box-shadow: 0 0 0 ${UiTokens.borderWidth.size3} ${thp.primary.level200._};
Done.

2023-01-03 13:50 UTC, sebastian-zeppelinlabs commented on src/components/Form/Checkbox/CheckboxStyles.ts
> -        border: 1px solid ${thp.base.level1000._};
Este es el checkbox que se comentó en su respectiva PR. Está aquí porque fue mi base para la configuración de los figma tokens.

2023-01-03 13:51 UTC, sebastian-zeppelinlabs commented on src/components/Form/Checkbox/CheckboxStyles.ts
> +    width: 70%;
Este es el checkbox que se comentó en su respectiva PR. Está aquí porque fue mi base para la configuración de los figma tokens.

2023-01-03 13:52 UTC, sebastian-zeppelinlabs commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> +        [RadioButtonSize.Small]: 16,
No estoy seguro de haber entendido. ¿Reemplazo lo que está hecho o agrego otra opción?

2023-01-03 13:54 UTC, sebastian-zeppelinlabs commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> +       box-shadow: 0 0 0 ${UiTokens.borderWidth.size3} ${thp.primary.level200._};
Done.

2023-01-03 13:57 UTC, sebastian-zeppelinlabs commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> -    max-width: 12px;
Fueron reemplazadas por las siguientes líneas de código: 
```
    width: ${p => getRadioSize(p.customStyles?.size || RadioButtonSize.Base)}px;
    height: ${p => getRadioSize(p.customStyles?.size || RadioButtonSize.Base)}px;
```
En caso de querer mantener los max y min, no tengo claro cuáles serían los valores, ni el porqué de mantenerlo.

2023-01-03 14:00 UTC, sebastian-zeppelinlabs commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> -    ErrorMessageContainer,
En src/components/Form/FormCommon.tsx, tenemos un renderErrorMessage común para los todos los componentes. Si no se usa en uno, no debería usarse en los demás, y así a la inversa.

2023-01-03 14:36 UTC, sebastian-zeppelinlabs commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> +        [RadioButtonSize.Small]: 16,
Probé este cambio y el resultado no fue el esperado, el tamaño del círculo interno no es el correcto.

2023-01-03 14:39 UTC, sebastian-zeppelinlabs commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> +        width: 50%;
Probé este cambio y el resultado no fue el esperado, el tamaño del círculo interno no es el correcto. 
Antes: 
<img width="326" alt="image" src="https://user-images.githubusercontent.com/115087599/210378505-4c7426a4-4d55-4510-b8da-672cb867578e.png">
Después: 
<img width="326" alt="image" src="https://user-images.githubusercontent.com/115087599/210378815-a2a2e8fd-d464-4ddf-8b87-558423e11eaa.png">

2023-01-03 18:40 UTC, ovveeerrrr commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> -    max-width: 12px;
El min width y max weight en este contexto lo estoy usando para asegurar que independiente el contexto no se deforme el circulo. Se ven redundantes las propiedades pero asi obligo a flex que cuando se quede sin espacio redimensione unicamente el contenido y no este circulo. el min width y max width como valor deberia recibir el mismo que el del width.

![Screenshot 2023-01-03 at 1 34 24 PM](https://user-images.githubusercontent.com/8033677/210420006-7e5ea119-49bf-48de-b597-6a806881f7d2.png)

Este lo use aqui unicamente cuando mi componente es tan generico que no controlo los posibles lugares donde va a estar. en otros casos no haria este hack ya que teniendo control del contexto entero puedo aplicar otras tecnicas

2023-01-03 18:51 UTC, ovveeerrrr commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> +        width: 50%;
A mi si me dio la medida. quizas el valor correcto en padding no es 5 si no 3 aproximado ya que el circulo interno tiene un borde de 2?
![Screenshot 2023-01-03 at 1 46 24 PM](https://user-images.githubusercontent.com/8033677/210421756-788b298e-cd59-412d-a6ec-83842a5141ff.png)

<img width="782" alt="Screenshot 2023-01-03 at 1 47 33 PM" src="https://user-images.githubusercontent.com/8033677/210421758-f5093cc2-fa67-4d83-a0c9-f961d0509a50.png">

con el estilo nuevo quizas (Prueba primero) ese borde sobra y queda mas comodo de calcular?

2023-01-03 18:52 UTC, ovveeerrrr commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> +        [RadioButtonSize.Small]: 16,
IDEM mas abajo. quizas cuestion de calculo y bordes?

2023-01-03 18:56 UTC, mateoZeppelin approved these changes

2023-01-04 16:30 UTC, sebastian-zeppelinlabs commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> +        [RadioButtonSize.Small]: 16,
Done.

2023-01-04 16:33 UTC, sebastian-zeppelinlabs commented on src/components/Form/RadioButton/RadioButtonStyles.ts
> -    max-width: 12px;
Gracias por la explicación. Aplico los cambios pertinentes. Done.

2023-01-04 20:30 UTC, ovveeerrrr approved these changes

2023-01-05 13:22 UTC, merged