Task/responsive
zeppelinlabs/util-components pull request #46
Opened 2023-01-30 14:42 UTC by sebastian-zeppelinlabs

2023-02-02 22:36 UTC, ovveeerrrr requested changes

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/Footer/FooterStyled.ts
> +	grid-template-rows: repeat(5, 1fr);
No me parece conveniente declarar rows aqui porque si luego agregamos o quitamos un boton va a quedar espacios en blanco o se comportara extraño, si no lo agrega quedaria rows infinitas y se ajustaria al contenido.

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/Footer/FooterStyled.ts
> +	grid-template-rows: repeat(5, 1fr);
Un adicional que te dejo a tu gusto, en version mobile y desktop no siento que sea necesario cambiar el tipo de display a flex a grid,directamente con grid podrias poner la cantidad de columnas necesarias y luego en mobile bajarlo a 1 columna. o en flex dejarlo como esta en desktop y en mobile probar algo con esta propiedad https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/Footer/Footer.tsx
> +			<img src={ZeppelinLabsLogo} alt="Zeppelin Labs" height={"30px"} />
este height en linea es para algo puntual? podemos replazarlo con css?

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/DetailComponentPage/DetailComponentPageStyled.ts
>  	flex-wrap: wrap;
cuando usas grid este flex-wrap pierde funcion. quizas seria mejor moverlo a la mediaqueire que tiene display flex ?

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/DetailComponentPage/DetailComponentPageStyled.ts
> +	display: grid;
por alguna razon se cambia el tipo de display para responsive? no le veo uso claro

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/DetailComponentPage/DetailComponentPageStyled.ts
> +		display: grid;
por alguna razon se cambia el tipo de display para responsive? no le veo uso claro

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/HomePage/HomePage.tsx
>  							UI tools to create whatever you want. Use our library full of production-ready components, or customize it as you need!
Estos textos se me pasaron porque agregue las traducciones al final. te animas a pasar estos textos a como lo manejamos en las paginas de cada componente asi dejamos todo disponible para rapidas traducciones. Aplica para todos los textos que vea en los componentes. la idea es que todos deben estar en los json

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	height: 3px;
creoq ue en el diseño es 2px el height

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	width: 75%;
es por algo puntual el 75%? podemos llevarlo a 100% y modificarlo si bien con algun padding en el padre o el width del padre?

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	transition: all .5s;
luego del .5s agregaria al menos un ease-out o el que te suene de esto: https://easings.net/. cuando no agrega el 3 paraemtro queda una animacion linear, sin embargo si agregamos una diferente a linear logramos mejor sensacion de movimiento

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	gap: .65rem;
me suena a que es mejor 4px? verifica las medidas con el figma

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/Header/HeaderStyled.ts
> +		display: flex;
este flex sobra porque ya esta mas arriba

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	z-index: ${zIndex.layer2};
para que se usa? que resuelve?

2023-02-02 22:36 UTC, ovveeerrrr commented on src/examples/_Layout/Header/HeaderStyled.ts
> +const ButtonLine = styled.div`
ya que no tiene gran impacto en el dom podemos cambiarlo de div a span? por el contexto creo que aplica mejor

2023-02-06 13:29 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/Header/HeaderStyled.ts
> +const ButtonLine = styled.div`
Done.

2023-02-06 13:34 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	z-index: ${zIndex.layer2};
El z-index es debido a que se debe sobre poner el contenido del search component por encima de los elementos fuera del del header, por eso tiene el mismo index que el header. El margen es para darle el aspecto del diseño
<img width="789" alt="image" src="https://user-images.githubusercontent.com/115087599/216984577-0161819b-35a8-4d57-814d-17bbfe664175.png">

2023-02-06 13:38 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/Header/HeaderStyled.ts
> +		display: flex;
Done.

2023-02-06 13:43 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	gap: .65rem;
No veo un espacio explícito en el diseño, por ahora prefiero mantenerlo así porque con 4px no se ve como se esperaba.

2023-02-06 13:47 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	transition: all .5s;
Done.

2023-02-06 13:50 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	width: 75%;
Es por la transición, las lineas forman la X y para lograr que la misma quede centrada me vino mejor usar esa unidad. Ejemplo 100% 
<img width="113" alt="image" src="https://user-images.githubusercontent.com/115087599/216988530-162af5f8-f8b0-437b-83ba-d4371f0002ae.png">

2023-02-06 19:11 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	transition: all .5s;
Done.

2023-02-06 21:58 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/HomePage/HomePage.tsx
> -						<TextStyled.Heading5xl textWeight="medium">
Done.

2023-02-06 21:58 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/HomePage/HomePageStyled.ts
> +const Title = styled.text`
Done.

2023-02-06 22:56 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/HomePage/HomePageStyled.ts
> +    grid-template-columns: repeat(4,1fr);
Done.

2023-02-07 14:36 UTC, sebarivero10 commented on src/examples/_Layout/Sidebar/SidebarSyled.ts
> +		transition: max-height .3s;
Está hecho así para que el accordion se vea mejor cuando se cierra.

2023-02-07 14:40 UTC, sebarivero10 commented on src/examples/_Layout/Sidebar/SidebarSyled.ts
> +const OverlayMenu = styled.div<{ isOpen: boolean, }>`
El overlayMenu está pensando para ocupar toda la pantalla y debe recibir un boolean que le indique si está abierto o no. El ContainerNavigation es el que se sitúa en la izquierda en la pantalla de componentes.

2023-02-08 23:59 UTC, ovveeerrrr commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	z-index: ${zIndex.layer2};
Entiendo sin embargo el z-index lo agregaria en HeaderStyled.SearchListOptions ya que al estar en el contenido desplegado mantenemos el layout natural sin z-index asi damos paso a que si necesitamos implementar z-index a otro elemento no se dispare la escala.

2023-02-09 00:02 UTC, ovveeerrrr commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	height: 80px;
Peligroso ese cambio a medida fija para mobile. entiendo el porque y esta bien usado pero creo que en los calculos del sidebar hay que actualizarlo?

ya que es numero fijo quizas puede guardar el numero en una constante y usarla aqui y en los calculos de los demas estilos lo haria mas facil de mantener?

![Screenshot 2023-02-08 at 6 53 48 PM](https://user-images.githubusercontent.com/8033677/217679219-569ea49a-6612-4cb8-baf7-4fbe51700939.png)

2023-02-09 16:21 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/HomePage/HomePage.tsx
>  							UI tools to create whatever you want. Use our library full of production-ready components, or customize it as you need!
Lo anoté como tarea para una próxima PR.

2023-02-09 16:22 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/DetailComponentPage/DetailComponentPageStyled.ts
> +	display: grid;
Es porque en el diseño los componentes del showcase se encuentran desplegados en una sola columna. Actualmente se utiliza el media query de tablet para cambiar el display a flex.

2023-02-09 16:27 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/Footer/Footer.tsx
> +			<img src={ZeppelinLabsLogo} alt="Zeppelin Labs" height={"30px"} />
Done.

2023-02-09 16:43 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/Footer/FooterStyled.ts
> +	grid-template-rows: repeat(5, 1fr);
Done.

2023-02-09 16:50 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/Header/HeaderStyled.ts
>  const ContainerSearchBar = styled.article`
Bien lo abarco para la próxima PR.

2023-02-09 20:16 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	height: 80px;
Done.

2023-02-09 20:37 UTC, ovveeerrrr approved these changes

2023-02-09 20:37 UTC, merged

2023-02-10 12:37 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/Header/HeaderStyled.ts
> +	height: 3px;
Done.

2023-02-10 12:40 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/DetailComponentPage/DetailComponentPageStyled.ts
>  	flex-wrap: wrap;
Done.