Add GitHub link to components
zeppelinlabs/util-components pull request #49
Opened 2023-02-10 16:35 UTC by sebastian-zeppelinlabs

2023-02-10 20:28 UTC, ovveeerrrr requested changes

2023-02-10 20:28 UTC, ovveeerrrr commented on src/examples/ButtonShowCase/ButtonShowCaseDetail.tsx
> +			githubLink={Paths.GithubComponents.Button}
En general para todos los componentes me queda la duda si esta bien apuntar directamente al .tsx del componente  Ej: https://github.com/zeppelinlabs/util-components/blob/dev/src/components/Button/Button.tsx o mejor a la carpeta que contiene la mayoria de archivos necesarios el componente .tsx y el archivo .ts con los estilos Ej: https://github.com/zeppelinlabs/util-components/tree/dev/src/components/Button 

Entiendo que en algunos componentes se ponga raro como en los inputs o no

2023-02-10 20:28 UTC, ovveeerrrr commented on src/examples/_Layout/DetailComponentPage/DetailComponentPageStyled.ts
> +`
le agregaria un gap:16px solo por si en algun caso a futuro el titulo es largo y se pega al boton tenga esa separacion minima

2023-02-10 20:28 UTC, ovveeerrrr commented on src/examples/_Layout/DetailComponentPage/DetailComponentPageStyled.ts
> +`
Esto aplica tambien para mobile

2023-02-10 20:28 UTC, ovveeerrrr commented on src/examples/_Layout/DetailComponentPage/DetailComponentPageStyled.ts
> +	display: inline-flex;
Como es un bloque y no un elemento en linea lo dejaria como display:flex no mas

2023-02-10 20:28 UTC, ovveeerrrr commented on src/examples/_Layout/DetailComponentPage/DetailComponentPageStyled.ts
> +const ContainerInLine = styled.div`
en lugar de que sea styled.div lo dejaria como styled.article para un poco de semantica en el html

2023-02-15 14:22 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/DetailComponentPage/DetailComponentPageStyled.ts
> +const ContainerInLine = styled.div`
Done.

2023-02-15 14:29 UTC, sebastian-zeppelinlabs commented on src/examples/_Layout/DetailComponentPage/DetailComponentPageStyled.ts
> +	display: inline-flex;
Done.

2023-02-18 01:07 UTC, sebastian-zeppelinlabs commented on src/examples/ButtonShowCase/ButtonShowCaseDetail.tsx
> +			githubLink={Paths.GithubComponents.Button}
Done.

2023-02-18 01:10 UTC, merged