Configuración de EsLint
zeppelinlabs/util-components pull request #5
Opened 2022-10-24 17:49 UTC by sebastian-zeppelinlabs

2022-10-24 18:34 UTC, mateoZeppelin approved these changes

2022-10-24 20:51 UTC, ovveeerrrr approved these changes

2022-10-24 21:24 UTC, Persitz requested changes
Dejo algunos comentarios

el package-lock.json podemos quitarlo, ya con el yarn.lock tenemos la info que necesitamos

2022-10-24 21:24 UTC, Persitz commented on .vscode/settings.json
> +  "typescript.tsdk": ".yarn/sdks/typescript/lib",
```
  "typescript.tsdk": ".yarn/sdks/typescript/lib",
  "typescript.enablePromptUseWorkspaceTsdk": true,
  ```
  
  no aplican en este proyecto, se usan cuando usas yarn con pnp/zero installs
  en este caso usamos "yarn normal"

2022-10-24 21:24 UTC, Persitz commented on .vscode/settings.json
> +  "files.exclude": {
```
"files.exclude": {
```
como estamos en el contexto de un create app, que "no transforma ts a js" no necesitamos estas reglas
es mejor quitarlas (y agregarlas cuando se necesiten) por que pueden esconder cierto tipo de errores que luego son dificiles de debugear (cuando se tiene un archivo js con el mismo nombre que otro ts o tsx create app puede tomar el js en lugar del ts y el vs code no nos va a mostrar el js)

2022-10-24 21:24 UTC, Persitz commented on .vscode/settings.json
> +  "eslint.workingDirectories": [
```"eslint.workingDirectories"```

en este proyecto no aplica esta config

2022-10-24 21:24 UTC, Persitz commented on .vscode/settings.json
> +  "eslint.nodePath": ".yarn/sdks",
"eslint.nodePath": ".yarn/sdks",

esta config es similar a `"typescript.tsdk": ".yarn/sdks/typescript/lib",` pero para eslin, no es necesario en este contexto

2022-10-24 21:24 UTC, Persitz commented on package.json
> +    "eslint-plugin-react-hooks": "^4.6.0"
creo que no es necesario

2022-10-26 19:34 UTC, sebastian-zeppelinlabs commented on .vscode/settings.json
> +  "typescript.tsdk": ".yarn/sdks/typescript/lib",
Done.

2022-10-26 19:34 UTC, sebastian-zeppelinlabs commented on .vscode/settings.json
> +  "files.exclude": {
Done.

2022-10-26 19:34 UTC, sebastian-zeppelinlabs commented on .vscode/settings.json
> +  "eslint.workingDirectories": [
Done.

2022-10-26 19:34 UTC, sebastian-zeppelinlabs commented on .vscode/settings.json
> +  "eslint.nodePath": ".yarn/sdks",
Done.

2022-10-26 19:35 UTC, sebastian-zeppelinlabs commented on package.json
> +    "eslint-plugin-react-hooks": "^4.6.0"
Done.

2022-10-26 19:43 UTC, merged