Agrega componente Tags
zeppelinlabs/util-components pull request #6
Opened 2022-10-25 22:34 UTC by ovveeerrrr

Agrega componente Tags junto a variantes en showcase

<img width="1339" alt="Screen Shot 2022-10-25 at 5 27 40 PM" src="https://user-images.githubusercontent.com/8033677/197894692-e400b2f6-40b2-40d5-943f-7871077cac20.png">

2022-10-26 22:28 UTC, Persitz commented on src/components/Tag/Tag.tsx
> +	onClickRemove?: () => void,
como son "practicamente botones", podemos pasar como parametro el evento, por si alguien tiene que hacer un prevent default, o similar
(o no, si les parece que mejor lo agrega el usuario si lo necesita)

2022-10-26 22:28 UTC, Persitz commented on src/components/Tag/Tag.tsx
> +	}
capas que podemos poner los params en minuscula? (menos IconSVGComponent que entiendo es un componente) 

IconSVGComponent es opcional si indicas que tiene icon?

2022-10-26 22:28 UTC, Persitz commented on src/components/Tag/Tag.tsx
> +	TextWeight?: TagTextWeight,
usa mayuscula por alguna razon?

2022-10-27 14:59 UTC, sebastian-zeppelinlabs commented on src/components/Tag/Tag.tsx
> +
Añadir Tag.displayName = "Tag"

2022-10-27 15:34 UTC, sebastian-zeppelinlabs requested changes

2022-10-27 15:34 UTC, sebastian-zeppelinlabs commented on src/Showcase.tsx
> +            <Tag Icon={{IconSVGComponent: EmailIcon,}} >
Este archivo está descontinuado, por lo que guardaría este código para usarlo en el showcase específico del componente.

2022-10-27 18:10 UTC, ovveeerrrr commented on src/components/Tag/Tag.tsx
> +	onClickRemove?: () => void,
Done, los agregue asi queda mas facil guiarse para editarlos

2022-10-27 18:16 UTC, ovveeerrrr commented on src/components/Tag/Tag.tsx
> +	}
Done, deje el icono opcional asi si alguien necesita modificar la posicion del icono (x) que se activa cuando existe la prop onClickRemove puede hacerlo sin magias raras ya que por default estaba a la derecha

![Screenshot 2022-10-27 at 1 13 47 PM](https://user-images.githubusercontent.com/8033677/198367483-3d78e138-71d3-4059-a25d-51524a33aa2c.png)

2022-10-27 18:16 UTC, ovveeerrrr commented on src/components/Tag/Tag.tsx
> +	TextWeight?: TagTextWeight,
Lag mental. Ajustado

2022-10-27 18:17 UTC, ovveeerrrr commented on src/components/Tag/Tag.tsx
> +
Done

2022-10-27 18:17 UTC, ovveeerrrr commented on src/Showcase.tsx
> +            <Tag Icon={{IconSVGComponent: EmailIcon,}} >
Ya lo quite esperando el ajuste del showcase

2022-10-28 16:54 UTC, sebastian-zeppelinlabs approved these changes

2022-10-31 16:34 UTC, Persitz approved these changes

2022-10-31 16:35 UTC, merged