Task/add state showcase
zeppelinlabs/util-components pull request #8
Opened 2022-10-27 15:29 UTC by sebastian-zeppelinlabs

2022-10-28 19:12 UTC, ovveeerrrr commented on src/showcase/Home.tsx
> +        <ShowCaseStyled.Wrapper>
ya que es el Home creo bueno cambiar el nombre del archivo de variable a Home ya que ShowCase se elimino

2022-10-28 19:12 UTC, ovveeerrrr commented on src/showcase/cases/SelectCase.tsx
> +export default SelectCase
Esto es de ejemplo? o es un componente puntual? me confunde que puede ser y la rutas a este componente. Showcase? cases?

2022-10-28 20:15 UTC, Persitz commented on src/index.tsx
> +        <React.StrictMode>
dejaria el strict mode afuera de todo

2022-10-28 20:16 UTC, Persitz requested changes

2022-10-28 20:16 UTC, Persitz commented on src/index.tsx
> +    <BrowserRouter>
dejaria el strict mode afuera de todo

2022-10-28 20:16 UTC, Persitz commented on src/showcase/Home.tsx
> +            <Link to={Paths.select}>Select</Link>
capas que se puede poner en la home un ejemplo de cada uno?
(dejaria dentro de SelectCase el contenido del ejemplo)

2022-10-29 00:04 UTC, sebastian-zeppelinlabs commented on src/index.tsx
> +    <BrowserRouter>
Done.

2022-10-31 19:59 UTC, Persitz commented on src/components/Form/Button/Button.tsx
>  import React from "react"
creo que el button no es particular de los forms

2022-10-31 19:59 UTC, Persitz commented on src/examples/Home.tsx
> +            <Link to={Paths.Button}>Button</Link>
podemos poner estas cosas en un array (definido mas arriba en este archivo), asi es mas facil agregar mas
lo mismo el App.tsx

2022-10-31 20:03 UTC, merged